### ISSUE TITLE
Prayer Times Calculation

### ISSUE THREAD

**Issue by kafiln** [choubari/Muslim-App#1]
Hello, and thank you for this awesome work.

Can you please tell me what is the calculation method for the prayer times ? 

Thanks

**Comment by choubari** [comment]
I used Muslim World League method with some offsets to adjust it better to Morocco Prayer Timings. 

I get the data from this api, check the link for more details: 
https://aladhan.com/prayer-times-api#GetCalendarByCitys

**Comment by kafiln** [comment]
Thanks, but how could you test that the times are accurate.

The muslim world league is very different from the method used in Morocco by the ministry.

I made an api the get the prayers for some cities in Morocco https://maroc-salat.herokuapp.com/

**Comment by Kafiil** [comment]
I love the design. Great Work.

Maybe you can contribue to this https://github.com/kafiil/salat, it has a really bad/boring design currently.

**Comment by choubari** [comment]
Thank you for your suggestions, as i'm targeting worldwide, I can't only implement the method used by the moroccan ministry. I found that Muslim World League will be accurate most of the times and if it isn't I added some manual corrections (maybe it's not the best solution and I need to treat each location by its method)
