### ISSUE TITLE
Fdroid

### ISSUE THREAD

**Issue by ahmed-tasaly** [choubari/Muslim-App#10]
@choubari 
**Assalam Alaykom**

### Can you add this to _Fdroid_ or to _IzzyOnDroid_?

example:
https://apt.izzysoft.de/fdroid/index/info

Thanks in advance

**Comment by ahmed-tasaly** [comment]
@choubari 
Reminding

**Comment by choubari** [comment]
Currently not interested in that.

Thank you for the suggestion
