### ISSUE TITLE
Azan not work 

### ISSUE THREAD

**Issue by ahmedaa6122** [choubari/Muslim-App#15]
When the time for prayer comes،  app not send me any notification

**Comment by choubari** [comment]
Yes, the Notifications doesn't work on devices of API level 26 and plus

**Comment by ahmedaa6122** [comment]
Can I contact with you telegram or whattsapp please

**Comment by choubari** [comment]
My Twitter Account: [twitter.com/choubari_](https://twitter.com/choubari_)
